import { useState } from 'react';

function generateTextReport(result) {
  let report = '═══════════════════════════════════════\n';
  report += '  AI TRANSCRIPT ANALYSIS REPORT\n';
  report += '  Generated by Trinethra Analyzer\n';
  report += '═══════════════════════════════════════\n\n';

  if (result.summary) {
    report += '📋 SUMMARY\n' + '─'.repeat(35) + '\n' + result.summary + '\n\n';
  }
  if (result.scores) {
    report += '📊 SCORES\n' + '─'.repeat(35) + '\n';
    Object.entries(result.scores).forEach(([k, v]) => {
      report += `  ${k.charAt(0).toUpperCase() + k.slice(1)}: ${v.score}/10 — ${v.reason}\n`;
    });
    report += '\n';
  }
  if (result.strengths?.length) {
    report += '✅ STRENGTHS\n' + '─'.repeat(35) + '\n';
    result.strengths.forEach((s, i) => { report += `  ${i + 1}. ${s}\n`; });
    report += '\n';
  }
  if (result.weaknesses?.length) {
    report += '⚠️ WEAKNESSES\n' + '─'.repeat(35) + '\n';
    result.weaknesses.forEach((w, i) => { report += `  ${i + 1}. ${w}\n`; });
    report += '\n';
  }
  if (result.recommendations?.length) {
    report += '💡 RECOMMENDATIONS\n' + '─'.repeat(35) + '\n';
    result.recommendations.forEach((r, i) => { report += `  ${i + 1}. ${r}\n`; });
    report += '\n';
  }
  if (result.follow_up_questions?.length) {
    report += '❓ FOLLOW-UP QUESTIONS\n' + '─'.repeat(35) + '\n';
    result.follow_up_questions.forEach((q, i) => { report += `  ${i + 1}. ${q}\n`; });
    report += '\n';
  }
  if (result.analyzed_at) {
    report += '─'.repeat(35) + '\nAnalyzed: ' + new Date(result.analyzed_at).toLocaleString() + '\n';
  }
  return report;
}

export default function ExportButtons({ result }) {
  const [copiedState, setCopiedState] = useState('');

  if (!result) return null;

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(generateTextReport(result));
      setCopiedState('copy');
      setTimeout(() => setCopiedState(''), 2000);
    } catch { /* ignore */ }
  };

  const handleDownloadJSON = () => {
    const blob = new Blob([JSON.stringify(result, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `analysis-${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
    setCopiedState('json');
    setTimeout(() => setCopiedState(''), 2000);
  };

  const handleDownloadTXT = () => {
    const blob = new Blob([generateTextReport(result)], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `analysis-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    setCopiedState('txt');
    setTimeout(() => setCopiedState(''), 2000);
  };

  return (
    <div className="export-buttons">
      <button className={`export-btn ${copiedState === 'copy' ? 'export-btn-success' : ''}`} onClick={handleCopy}>
        {copiedState === 'copy' ? '✓ Copied' : '📋 Copy'}
      </button>
      <button className={`export-btn ${copiedState === 'json' ? 'export-btn-success' : ''}`} onClick={handleDownloadJSON}>
        {copiedState === 'json' ? '✓ Saved' : '⬇ JSON'}
      </button>
      <button className={`export-btn ${copiedState === 'txt' ? 'export-btn-success' : ''}`} onClick={handleDownloadTXT}>
        {copiedState === 'txt' ? '✓ Saved' : '📄 TXT'}
      </button>
    </div>
  );
}
